namespace SalaryCalculator
{
	public abstract partial class ExchangeRateProvider<T> : IExchangeRateProvider<T> where T : IExchangeRate
	{
		public static readonly Dictionary<CurrencyCode, string> CurrencyNames = new()
		{
			{ CurrencyCode.AED, "United Arab Emirates dirham" },
			{ CurrencyCode.AFN, "Afghan afghani" },
			{ CurrencyCode.ALL, "Albanian lek" },
			{ CurrencyCode.AMD, "Armenian dram" },
			{ CurrencyCode.ANG, "Netherlands Antillean guilder" },
			{ CurrencyCode.AOA, "Angolan kwanza" },
			{ CurrencyCode.ARS, "Argentine peso" },
			{ CurrencyCode.AUD, "Australian dollar" },
			{ CurrencyCode.AWG, "Aruban florin" },
			{ CurrencyCode.AZN, "Azerbaijani manat" },
			{ CurrencyCode.BAM, "Bosnia and Herzegovina convertible mark" },
			{ CurrencyCode.BBD, "Barbados dollar" },
			{ CurrencyCode.BDT, "Bangladeshi taka" },
			{ CurrencyCode.BGN, "Bulgarian lev" },
			{ CurrencyCode.BHD, "Bahraini dinar" },
			{ CurrencyCode.BIF, "Burundian franc" },
			{ CurrencyCode.BMD, "Bermudian dollar" },
			{ CurrencyCode.BND, "Brunei dollar" },
			{ CurrencyCode.BOB, "Boliviano" },
			{ CurrencyCode.BOV, "Bolivian Mvdol (funds code)" },
			{ CurrencyCode.BRL, "Brazilian real" },
			{ CurrencyCode.BSD, "Bahamian dollar" },
			{ CurrencyCode.BTN, "Bhutanese ngultrum" },
			{ CurrencyCode.BWP, "Botswana pula" },
			{ CurrencyCode.BYN, "Belarusian ruble" },
			{ CurrencyCode.BZD, "Belize dollar" },
			{ CurrencyCode.CAD, "Canadian dollar" },
			{ CurrencyCode.CDF, "Congolese franc" },
			{ CurrencyCode.CHE, "WIR euro (complementary currency)" },
			{ CurrencyCode.CHF, "Swiss franc" },
			{ CurrencyCode.CHW, "WIR franc (complementary currency)" },
			{ CurrencyCode.CLF, "Unidad de Fomento (funds code)" },
			{ CurrencyCode.CLP, "Chilean peso" },
			{ CurrencyCode.CNY, "Chinese yuan" },
			{ CurrencyCode.COP, "Colombian peso" },
			{ CurrencyCode.COU, "Unidad de Valor Real (UVR) (funds code)" },
			{ CurrencyCode.CRC, "Costa Rican colon" },
			{ CurrencyCode.CUC, "Cuban convertible peso" },
			{ CurrencyCode.CUP, "Cuban peso" },
			{ CurrencyCode.CVE, "Cape Verdean escudo" },
			{ CurrencyCode.CZK, "Czech koruna" },
			{ CurrencyCode.DJF, "Djiboutian franc" },
			{ CurrencyCode.DKK, "Danish krone" },
			{ CurrencyCode.DOP, "Dominican peso" },
			{ CurrencyCode.DZD, "Algerian dinar" },
			{ CurrencyCode.EGP, "Egyptian pound" },
			{ CurrencyCode.ERN, "Eritrean nakfa" },
			{ CurrencyCode.ETB, "Ethiopian birr" },
			{ CurrencyCode.EUR, "Euro" },
			{ CurrencyCode.FJD, "Fiji dollar" },
			{ CurrencyCode.FKP, "Falkland Islands pound" },
			{ CurrencyCode.GBP, "Pound sterling" },
			{ CurrencyCode.GEL, "Georgian lari" },
			{ CurrencyCode.GHS, "Ghanaian cedi" },
			{ CurrencyCode.GIP, "Gibraltar pound" },
			{ CurrencyCode.GMD, "Gambian dalasi" },
			{ CurrencyCode.GNF, "Guinean franc" },
			{ CurrencyCode.GTQ, "Guatemalan quetzal" },
			{ CurrencyCode.GYD, "Guyanese dollar" },
			{ CurrencyCode.HKD, "Hong Kong dollar" },
			{ CurrencyCode.HNL, "Honduran lempira" },
			{ CurrencyCode.HRK, "Croatian kuna" },
			{ CurrencyCode.HTG, "Haitian gourde" },
			{ CurrencyCode.HUF, "Hungarian forint" },
			{ CurrencyCode.IDR, "Indonesian rupiah" },
			{ CurrencyCode.ILS, "Israeli new shekel" },
			{ CurrencyCode.INR, "Indian rupee" },
			{ CurrencyCode.IQD, "Iraqi dinar" },
			{ CurrencyCode.IRR, "Iranian rial" },
			{ CurrencyCode.ISK, "Icelandic króna (plural: krónur)" },
			{ CurrencyCode.JMD, "Jamaican dollar" },
			{ CurrencyCode.JOD, "Jordanian dinar" },
			{ CurrencyCode.JPY, "Japanese yen" },
			{ CurrencyCode.KES, "Kenyan shilling" },
			{ CurrencyCode.KGS, "Kyrgyzstani som" },
			{ CurrencyCode.KHR, "Cambodian riel" },
			{ CurrencyCode.KMF, "Comoro franc" },
			{ CurrencyCode.KPW, "North Korean won" },
			{ CurrencyCode.KRW, "South Korean won" },
			{ CurrencyCode.KWD, "Kuwaiti dinar" },
			{ CurrencyCode.KYD, "Cayman Islands dollar" },
			{ CurrencyCode.KZT, "Kazakhstani tenge" },
			{ CurrencyCode.LAK, "Lao kip" },
			{ CurrencyCode.LBP, "Lebanese pound" },
			{ CurrencyCode.LKR, "Sri Lankan rupee" },
			{ CurrencyCode.LRD, "Liberian dollar" },
			{ CurrencyCode.LSL, "Lesotho loti" },
			{ CurrencyCode.LYD, "Libyan dinar" },
			{ CurrencyCode.MAD, "Moroccan dirham" },
			{ CurrencyCode.MDL, "Moldovan leu" },
			{ CurrencyCode.MGA, "Malagasy ariary" },
			{ CurrencyCode.MKD, "Macedonian denar" },
			{ CurrencyCode.MMK, "Myanmar kyat" },
			{ CurrencyCode.MNT, "Mongolian tögrög" },
			{ CurrencyCode.MOP, "Macanese pataca" },
			{ CurrencyCode.MRU, "Mauritanian ouguiya" },
			{ CurrencyCode.MUR, "Mauritian rupee" },
			{ CurrencyCode.MVR, "Maldivian rufiyaa" },
			{ CurrencyCode.MWK, "Malawian kwacha" },
			{ CurrencyCode.MXN, "Mexican peso" },
			{ CurrencyCode.MXV, "Mexican Unidad de Inversion (UDI) (funds code)" },
			{ CurrencyCode.MYR, "Malaysian ringgit" },
			{ CurrencyCode.MZN, "Mozambican metical" },
			{ CurrencyCode.NAD, "Namibian dollar" },
			{ CurrencyCode.NGN, "Nigerian naira" },
			{ CurrencyCode.NIO, "Nicaraguan córdoba" },
			{ CurrencyCode.NOK, "Norwegian krone" },
			{ CurrencyCode.NPR, "Nepalese rupee" },
			{ CurrencyCode.NZD, "New Zealand dollar" },
			{ CurrencyCode.OMR, "Omani rial" },
			{ CurrencyCode.PAB, "Panamanian balboa" },
			{ CurrencyCode.PEN, "Peruvian sol" },
			{ CurrencyCode.PGK, "Papua New Guinean kina" },
			{ CurrencyCode.PHP, "Philippine peso" },
			{ CurrencyCode.PKR, "Pakistani rupee" },
			{ CurrencyCode.PLN, "Polish złoty" },
			{ CurrencyCode.PYG, "Paraguayan guaraní" },
			{ CurrencyCode.QAR, "Qatari riyal" },
			{ CurrencyCode.RON, "Romanian leu" },
			{ CurrencyCode.RSD, "Serbian dinar" },
			{ CurrencyCode.RUB, "Russian ruble" },
			{ CurrencyCode.RWF, "Rwandan franc" },
			{ CurrencyCode.SAR, "Saudi riyal" },
			{ CurrencyCode.SBD, "Solomon Islands dollar" },
			{ CurrencyCode.SCR, "Seychelles rupee" },
			{ CurrencyCode.SDG, "Sudanese pound" },
			{ CurrencyCode.SEK, "Swedish krona (plural: kronor)" },
			{ CurrencyCode.SGD, "Singapore dollar" },
			{ CurrencyCode.SHP, "Saint Helena pound" },
			{ CurrencyCode.SLL, "Sierra Leonean leone" },
			{ CurrencyCode.SOS, "Somali shilling" },
			{ CurrencyCode.SRD, "Surinamese dollar" },
			{ CurrencyCode.SSP, "South Sudanese pound" },
			{ CurrencyCode.STN, "São Tomé and Príncipe dobra" },
			{ CurrencyCode.SVC, "Salvadoran colón" },
			{ CurrencyCode.SYP, "Syrian pound" },
			{ CurrencyCode.SZL, "Swazi lilangeni" },
			{ CurrencyCode.THB, "Thai baht" },
			{ CurrencyCode.TJS, "Tajikistani somoni" },
			{ CurrencyCode.TMT, "Turkmenistan manat" },
			{ CurrencyCode.TND, "Tunisian dinar" },
			{ CurrencyCode.TOP, "Tongan paʻanga" },
			{ CurrencyCode.TRY, "Turkish lira" },
			{ CurrencyCode.TTD, "Trinidad and Tobago dollar" },
			{ CurrencyCode.TWD, "New Taiwan dollar" },
			{ CurrencyCode.TZS, "Tanzanian shilling" },
			{ CurrencyCode.UAH, "Ukrainian hryvnia" },
			{ CurrencyCode.UGX, "Ugandan shilling" },
			{ CurrencyCode.USD, "United States dollar" },
			{ CurrencyCode.USN, "United States dollar (next day) (funds code)" },
			{ CurrencyCode.UYI, "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)" },
			{ CurrencyCode.UYU, "Uruguayan peso" },
			{ CurrencyCode.UYW, "Unidad previsional" },
			{ CurrencyCode.UZS, "Uzbekistan som" },
			{ CurrencyCode.VED, "Venezuelan bolívar digital" },
			{ CurrencyCode.VES, "Venezuelan bolívar soberano" },
			{ CurrencyCode.VND, "Vietnamese đồng" },
			{ CurrencyCode.VUV, "Vanuatu vatu" },
			{ CurrencyCode.WST, "Samoan tala" },
			{ CurrencyCode.XAF, "CFA franc BEAC" },
			{ CurrencyCode.XAG, "Silver (one troy ounce)" },
			{ CurrencyCode.XAU, "Gold (one troy ounce)" },
			{ CurrencyCode.XBA, "European Composite Unit (EURCO) (bond market unit)" },
			{ CurrencyCode.XBB, "European Monetary Unit (E.M.U.-6) (bond market unit)" },
			{ CurrencyCode.XBC, "European Unit of Account 9 (E.U.A.-9) (bond market unit)" },
			{ CurrencyCode.XBD, "European Unit of Account 17 (E.U.A.-17) (bond market unit)" },
			{ CurrencyCode.XCD, "East Caribbean dollar" },
			{ CurrencyCode.XDR, "Special drawing rights" },
			{ CurrencyCode.XOF, "CFA franc BCEAO" },
			{ CurrencyCode.XPD, "Palladium (one troy ounce)" },
			{ CurrencyCode.XPF, "CFP franc (franc Pacifique)" },
			{ CurrencyCode.XPT, "Platinum (one troy ounce)" },
			{ CurrencyCode.XSU, "SUCRE" },
			{ CurrencyCode.XTS, "Code reserved for testing" },
			{ CurrencyCode.XUA, "ADB Unit of Account" },
			{ CurrencyCode.XXX, "No currency" },
			{ CurrencyCode.YER, "Yemeni rial" },
			{ CurrencyCode.ZAR, "South African rand" },
			{ CurrencyCode.ZMW, "Zambian kwacha" },
			{ CurrencyCode.ZWL, "Zimbabwean dollar" }
		};
	}
}
